appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: appveyor}
travis:
  secure: {BINSTAR_TOKEN: X66STAz1m5doQkEvZ47Lc+I2DIzTk1pcR2eNh7C7YQSJy8X+LR6sdoGbRl8bLsEU/DjNuAV2e3EnqxAPhMnCT8zqKt0TCPkA6BOT7FbEYDwvuX8hoDWFaMlL3Nf7+YPTAwGz3G3COCbVXBue9jcb8/9lBER5cBJ/W7jFQGw9BfGVv3yv5xHUY6KiJ3jMZUT1zJwL0FkNiNPw8arzm6WAVpf2Cw0/t/A2ykQ0MLM6y363kpKllVVcFQnYDcEVINXhb/7qE1MiPuORW9m8SQl8QZYdnwa0GhVKJOHSm3i7+FGpUxXeGKFX/cpdftEyfwKtQEOwIp6oAn8Vga7Mnp1A1fiexPScp7x91y2kVG+OoWNE+v6xHqwBySU7G/rfGfRb2EGxdCdEwA5GWmFZsys0jQQEOYFQwiAtQZirH1ohYND78veYFkNkX4Xo3FiB7uanBESzpcFCjvPJvxnC8tLhUX9CLk8wtegyYtNoDgceO1mwA6XMaiLeM3lF1ik+ck0gnKnNu66wmykzyDXFOpAFlBeh5gO/bxCeTHHb+tzq9XIbkosO/bQ044rKk7e2Jgg7zNdOz/7zXlHHusBFU12E15WluAT0Z1sy0y6ZENhA5wJ1+3wuBTt5fFQnY+d6RPvE8O1RKaI6ZumCvIGp5cWkMArG7sT9Rldprzw0vDMQJ5Q=}
