bot:
  automerge: true
conda_forge_output_validation: true
test: native_and_emulated
provider:
  linux_aarch64: default
  linux_ppc64le: azure
  win: azure
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
